/**
 * Sunfizz flavour palette. Colours match the packshots generated by
 * catalog/tools/generate-catalog.mjs. Products are matched by their Shopify
 * tag (orange / grapefruit / lemon / lime / variety), so a renamed product
 * keeps its colours as long as the tag stays.
 */
export type FlavourKey = 'orange' | 'grapefruit' | 'lemon' | 'lime' | 'variety';

export type Ingredient = {
  name: string;
  kind: 'citrus' | 'flower' | 'leaf' | 'botanical';
};

export type Flavour = {
  key: FlavourKey;
  /** Short name for swatches. */
  label: string;
  /** Tasting notes, e.g. "Orange, tangerine & ginger". */
  notes: string;
  ingredients: Ingredient[];
  /** Can body gradient: edge, mid, highlight, far edge. */
  body: [string, string, string, string];
  /** Accent text/ink on cream (AA for large text). */
  accent: string;
  peel: string;
  flesh: string;
  /** Text printed on the coloured part of the can. */
  bodyText: string;
  /** Page tints behind the product. */
  bg: string;
  bgLight: string;
  /** Printed on the can's flavour pill. */
  canLabel: string;
};

const INK = '#2a1409';

/** The collection whose products are the flavour swatches on product pages. */
export const FLAVOUR_COLLECTION_HANDLE = 'sparkling-tonics';

export const FLAVOURS: Record<Exclude<FlavourKey, 'variety'>, Flavour> = {
  orange: {
    key: 'orange',
    label: 'Citrus Sunrise',
    notes: 'Orange, tangerine & ginger',
    ingredients: [
      {name: 'Orange', kind: 'citrus'},
      {name: 'Tangerine', kind: 'citrus'},
      {name: 'Ginger', kind: 'botanical'},
    ],
    body: ['#d4460a', '#ff7a1a', '#ff9d48', '#c43f09'],
    accent: '#c2410c',
    peel: '#ff9f2e',
    flesh: '#ffc56b',
    bodyText: '#fff',
    bg: '#ffd9bd',
    bgLight: '#fff1e4',
    canLabel: 'CITRUS SUNRISE',
  },
  grapefruit: {
    key: 'grapefruit',
    label: 'Pink Grapefruit',
    notes: 'Pink grapefruit & hibiscus',
    ingredients: [
      {name: 'Pink grapefruit', kind: 'citrus'},
      {name: 'Hibiscus', kind: 'flower'},
    ],
    body: ['#c42f40', '#ff5a5f', '#ff8a8c', '#b02736'],
    accent: '#c02739',
    peel: '#ff6f73',
    flesh: '#ffb3b5',
    bodyText: '#fff',
    bg: '#ffd3d5',
    bgLight: '#fff0f0',
    canLabel: 'PINK GRAPEFRUIT',
  },
  lemon: {
    key: 'lemon',
    label: 'Lemon Zest',
    notes: 'Sicilian lemon & garden mint',
    ingredients: [
      {name: 'Sicilian lemon', kind: 'citrus'},
      {name: 'Garden mint', kind: 'leaf'},
    ],
    body: ['#d9a300', '#ffd23f', '#ffe588', '#c99500'],
    accent: '#876400',
    peel: '#ffd23f',
    flesh: '#fff0a3',
    bodyText: INK,
    bg: '#ffeaa1',
    bgLight: '#fff9e0',
    canLabel: 'LEMON ZEST',
  },
  lime: {
    key: 'lime',
    label: 'Lime Crush',
    notes: 'Key lime & cucumber',
    ingredients: [
      {name: 'Key lime', kind: 'citrus'},
      {name: 'Cucumber', kind: 'botanical'},
    ],
    body: ['#4b9420', '#7cc242', '#a8e04c', '#3f841a'],
    accent: '#3a7512',
    peel: '#8fd14f',
    flesh: '#d4f39a',
    bodyText: INK,
    bg: '#dcf2c2',
    bgLight: '#f4fbe9',
    canLabel: 'LIME CRUSH',
  },
};

export const FLAVOUR_ORDER = ['orange', 'grapefruit', 'lemon', 'lime'] as const;

/** The mixed pack borrows its cans from the four flavours. */
export const VARIETY = {
  key: 'variety' as const,
  label: 'Variety Pack',
  notes: 'All four flavours in one box',
  ingredients: FLAVOUR_ORDER.map((k) => ({
    name: FLAVOURS[k].label,
    kind: 'citrus' as const,
  })),
  accent: '#c2410c',
  bg: '#ffe7b8',
  bgLight: '#fff8ea',
};

export type FlavourLike = Flavour | typeof VARIETY;

export function flavourKeyFromTags(tags: readonly string[] | undefined): FlavourKey | null {
  if (!tags) return null;
  const lower = tags.map((t) => t.toLowerCase());
  if (lower.includes('variety')) return 'variety';
  return FLAVOUR_ORDER.find((k) => lower.includes(k)) ?? null;
}

export function flavourFor(tags: readonly string[] | undefined): FlavourLike | null {
  const key = flavourKeyFromTags(tags);
  if (!key) return null;
  return key === 'variety' ? VARIETY : FLAVOURS[key];
}

/** Sort products into the house order: the four flavours, then the variety pack, then anything else. */
export function byFlavourOrder<T extends {tags: readonly string[]}>(products: readonly T[]): T[] {
  const rank = (p: T) => {
    const key = flavourKeyFromTags(p.tags);
    if (key === 'variety') return FLAVOUR_ORDER.length;
    return key ? FLAVOUR_ORDER.indexOf(key) : FLAVOUR_ORDER.length + 1;
  };
  return [...products].sort((a, b) => rank(a) - rank(b));
}

/** CSS custom properties that tint a product's surroundings. */
export function flavourStyle(flavour: FlavourLike | null): React.CSSProperties {
  if (!flavour) return {};
  return {
    '--f-bg': flavour.bg,
    '--f-bg-light': flavour.bgLight,
    '--f-accent': flavour.accent,
    '--f-swatch':
      flavour.key === 'variety'
        ? `conic-gradient(${FLAVOUR_ORDER.map((k, i) => `${FLAVOURS[k].body[1]} ${i * 25}% ${(i + 1) * 25}%`).join(', ')})`
        : flavour.body[1],
  } as React.CSSProperties;
}
